#!/usr/bin/env python3
"""Provision and remove anonymous synthetic accounts for the LAN HCI study."""

from __future__ import annotations

import argparse
import asyncio
import re
import secrets
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps/api"
RUNTIME_ACCOUNTS = ROOT / ".runtime" / "hci" / "accounts"
CONFIRMATION = "--confirm-isolated-staging"


class AccountOperationError(RuntimeError):
    pass


def _participant_identity(participant_code: str) -> tuple[str, str]:
    if re.fullmatch(r"P-[A-F0-9]{8}", participant_code) is None:
        raise AccountOperationError("participant code must be generated by the HCI study tool")
    marker = participant_code.removeprefix("P-").lower()
    return f"hci-{marker}@example.invalid", f"HCI Study {participant_code}"


def _private_output(path: Path) -> Path:
    resolved = path.expanduser().resolve()
    if not resolved.is_relative_to(RUNTIME_ACCOUNTS.resolve()):
        raise AccountOperationError("credential output must remain under .runtime/hci/accounts")
    return resolved


def _participant_credentials_path(participant_code: str, path: Path) -> Path:
    _participant_identity(participant_code)
    resolved = _private_output(path)
    expected = (RUNTIME_ACCOUNTS / f"{participant_code}.env").resolve()
    if resolved != expected:
        raise AccountOperationError("credential filename must match the anonymous participant code")
    return resolved


def _validate_staging(settings) -> None:
    if settings.app_environment != "production":
        raise AccountOperationError("HCI account operations require production-shaped staging")
    if settings.database_name != "witscraft_staging":
        raise AccountOperationError("HCI account operations refuse a non-staging database")
    if settings.database_host not in {"127.0.0.1", "localhost"}:
        raise AccountOperationError("HCI account operations require a loopback database backend")
    if settings.database_ssl_mode != "require":
        raise AccountOperationError("HCI account operations require database TLS")
    if not settings.frontend_base_url.startswith("https://"):
        raise AccountOperationError("HCI account operations require the LAN HTTPS candidate")


def _write_credentials(path: Path, participant_code: str, email: str, password: str) -> None:
    if path.exists():
        raise AccountOperationError("credential output already exists")
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        "\n".join(
            (
                f"HCI_PARTICIPANT_CODE={participant_code}",
                f"HCI_SYNTHETIC_EMAIL={email}",
                f"HCI_SYNTHETIC_PASSWORD={password}",
                "",
            )
        ),
        encoding="utf-8",
    )
    temporary.chmod(0o600)
    temporary.replace(path)


async def _create(participant_code: str, output: Path) -> None:
    sys.path.insert(0, str(API_ROOT))
    from sqlalchemy import func, select

    from app.config import get_settings
    from app.db.models import AuthCredential, User
    from app.db.session import AsyncSessionLocal, engine
    from app.services.auth_service import hash_password

    settings = get_settings()
    _validate_staging(settings)
    email, display_name = _participant_identity(participant_code)
    password = secrets.token_urlsafe(32)
    user_id = None
    try:
        async with AsyncSessionLocal() as session:
            existing = await session.scalar(
                select(func.count()).select_from(User).where(func.lower(User.email) == email)
            )
            if existing:
                raise AccountOperationError("synthetic participant account already exists")
            user = User(
                email=email,
                display_name=display_name,
                email_verified_at=datetime.now(timezone.utc),
                is_admin=False,
            )
            session.add(user)
            await session.flush()
            user_id = user.id
            session.add(AuthCredential(user_id=user.id, password_hash=hash_password(password)))
            await session.commit()
        try:
            _write_credentials(output, participant_code, email, password)
        except Exception:
            async with AsyncSessionLocal() as session:
                user = await session.get(User, user_id)
                if user is not None:
                    await session.delete(user)
                    await session.commit()
            raise
    finally:
        await engine.dispose()


async def _delete(participant_code: str, credentials: Path) -> None:
    sys.path.insert(0, str(API_ROOT))
    from sqlalchemy import delete, func, select

    from app.config import get_settings
    from app.db.models import User
    from app.db.session import AsyncSessionLocal, engine

    settings = get_settings()
    _validate_staging(settings)
    email, display_name = _participant_identity(participant_code)
    try:
        async with AsyncSessionLocal() as session:
            user = await session.scalar(
                select(User).where(User.email == email, User.display_name == display_name).limit(1)
            )
            if user is None:
                raise AccountOperationError("synthetic participant account was not found")
            user_id = user.id
            await session.execute(delete(User).where(User.id == user_id))
            await session.commit()
            remaining = await session.scalar(
                select(func.count()).select_from(User).where(User.id == user_id)
            )
            if remaining:
                raise AccountOperationError("synthetic participant account cleanup failed")
        if credentials.exists():
            credentials.unlink()
    finally:
        await engine.dispose()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(CONFIRMATION, action="store_true", required=True)
    subparsers = parser.add_subparsers(dest="command", required=True)
    create = subparsers.add_parser("create")
    create.add_argument("--participant-code", required=True)
    create.add_argument("--output", type=Path, required=True)
    delete_parser = subparsers.add_parser("delete")
    delete_parser.add_argument("--participant-code", required=True)
    delete_parser.add_argument("--credentials", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    try:
        if args.command == "create":
            output = _participant_credentials_path(args.participant_code, args.output)
            asyncio.run(_create(args.participant_code, output))
            print(f"Synthetic HCI account created; private credentials: {output}")
        else:
            credentials = _participant_credentials_path(args.participant_code, args.credentials)
            asyncio.run(_delete(args.participant_code, credentials))
            print("Synthetic HCI account and private credential file deleted")
    except (AccountOperationError, OSError) as exc:
        raise SystemExit(f"HCI account operation rejected: {exc}") from None


if __name__ == "__main__":
    main()
